Fix the tokenizer template error (#10)
The trainer is failing because of the following error surfaced in the
following issue
https://github.com/horus-ai-labs/DistillFlow/issues/9

```
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/Users/akashdeepjassal/Desktop/exp/DistillFlow/src/trainer.py", line 119, in <module>
    main()
  File "/Users/akashdeepjassal/Desktop/exp/DistillFlow/src/trainer.py", line 61, in main
    tokenizer_template = config.tokenizer.template
                         ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/distill/lib/python3.12/site-packages/pydantic/main.py", line 891, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Config' object has no attribute 'tokenizer' 
```

This block is duplicated on line 85 and no longer required.